### ISSUE TITLE
iOS crash with advanced alert payload

### ISSUE THREAD

**Issue by jerone** [KSemenenko/AzurePushNotificationsForXamarinForms#2]
I need to use the advanced payload for my push notifications. As the [documentation](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/PayloadKeyReference.html) says, and `alert` property can be an `NSString` or an `NSDictionary` with [child properties](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/PayloadKeyReference.html#//apple_ref/doc/uid/TP40008194-CH17-SW5).

But as soon as I use the advanced payload your plugin crashes with:
>`System.NullReferenceException: Object reference not set to an instance of an object`.

Looking through your code I found a reference to this subject [here](https://github.com/KSemenenko/AzurePushNotificationsForXamarinForms/blob/e5338cc455d8c014e8bfbdf9412de0db296da488/Plugin.AzurePushNotifications/Plugin.AzurePushNotifications.iOS/AzurePushNotificationsImplementation.cs#L78-L88). But I wouldn't expect it to crash.

A simple solution would be to alter that code with the following (_untested_):
```diff
if(aps.ContainsKey(new NSString("alert")))
{
-    alert = (aps[new NSString("alert")] as NSString).ToString();
+    alert = (aps[new NSString("alert")] as NSString) ?? "";
}
```

Thinking even further, I don't want to show an alert there at all. I want to execute my own logic through the `OnMessageReceived` event.

Can you at least fix above bug or make the build-in alert **optional**.

**Comment by KSemenenko** [comment]
ok!I'll do it one of these days!
