### ISSUE TITLE
Update nuget

### ISSUE THREAD

**Issue by jzhouw** [KSemenenko/AzurePushNotificationsForXamarinForms#7]
Hi @KSemenenko can you please update the nuget to latest, I don't want the build-in alert for the ios on notification and I have noticed this has been disabled in latest commit here 
https://github.com/KSemenenko/AzurePushNotificationsForXamarinForms/commit/0698f5ea9aeedf109ee43c441701449e791a9242

Thanks

**Comment by KSemenenko** [comment]
Hi! @jamesatgithub 
You can specify, you want me to just update the package. Or rolled back the last comit?

**Comment by jzhouw** [comment]
hi @KSemenenko I wanted the feature in the latest commit (the ios alert commented out), so just update nuget

**Comment by jzhouw** [comment]
btw I don't like alert because it doesn't support localization, better this could be a optional and support localization in future

**Comment by KSemenenko** [comment]
Done!
please check new version 0.0.4.6 in Nuget

**Comment by KSemenenko** [comment]
I think we should use https://docs.microsoft.com/en-us/mobile-center/push/
It looks better than my library))
